[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_nn"
version = "0.1.0"
description = "A simple neural network library for learning and experimentation"
authors = [
    {name="Ron Sperber"}
]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn"
]

[tool.setuptools]
packages = ["my_nn"]
