# sample_data.py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

# This is meant to generate some specific sample data to test neural networks with
# There are 4 sample targets generated, all using the same value for X

def generate_data(n_samples=10000, seed=None, filename = None, overwrite=False):
    # set a random see for reproducibility if desired
    if seed is not None:
        np.random.seed(seed)
    # pick 10000 points in [-5,5] x [-5,5]
    X = np.random.uniform(-5, 5, size=(n_samples, 2))
    
    # create targets
    # binary with a parabolic decision boundary
    y_binary = (X[:, 1] - X[:, 0] ** 2 >= -2).astype(int)
    # binary with a piecewise linear decision boundary
    y_binary_pl = (X[:, 1] - np.abs(X[:, 0]) >= -2).astype(int)
    # creating a multiclass target with decision boundary two branches of a hyperbola.
    # Above top branch is class 1, below bottom branch is class 2, in between is class 0
    mask1 = (X[:, 1] ** 2 - X[:, 0] ** 2 >= 3) & (X[:, 1] > 0)
    mask2 = (X[:, 1] ** 2 - X[:, 0] ** 2 >= 3) & (X[:, 1] < 0)
    y_multiclass = mask1 + 2 * mask2
    # for regression use z = x**2 + y**2
    y_regression = np.sum(X**2, axis=1)

    # create a single DataFrame with all targets
    df = pd.DataFrame({
        "x1": X[:, 0],
        "x2": X[:, 1],
        "binary_parabola": y_binary,
        "binary_pl": y_binary_pl,
        "multiclass": y_multiclass,
        "regression": y_regression,
    })
    if filename is not None:
        if os.path.exists(filename) and not overwrite:
            raise FileExistsError(
                f"{filename} already exists. Pass overwrite=True to overwrite it."
            )
        df.to_csv(filename, index=False)
        print(f"Data saved to {filename}")
    target_cols = ["binary_parabola", "binary_pl", "multiclass", "regression"]
    return df, target_cols


def save_data(filename="sample_data.csv", n_samples=10000, seed=None):
    df = generate_data(n_samples=n_samples, seed=seed)
    df.to_csv(filename, index=False)
    return filename



def plot_data(df, target="binary_parabola", sample=2000):
    """
    Quick scatter plot of X vs chosen target.
    - df: DataFrame generated by generate_data()
    - target: which column to color by (binary_parabola, binary_pl, multiclass, regression)
    - sample: number of points to plot (for speed)
    """
    if sample and len(df) > sample:
        df = df.sample(sample, random_state=0)

    x = df["x1"].values
    y = df["x2"].values
    c = df[target].values

    plt.figure(figsize=(6, 6))
    if target == "regression":
        scatter = plt.scatter(x, y, c=c, cmap="viridis", s=5)
        plt.colorbar(scatter, label=target)
    else:
        plt.scatter(x, y, c=c, cmap="coolwarm", s=5)
    plt.xlabel("x1")
    plt.ylabel("x2")
    plt.title(f"Sample Data - {target}")
    plt.show()

